name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Add rustup target
        run: rustup target add ${{ matrix.target }}

      - name: Build ${{ matrix.target }}
        run: cargo build --release --target=${{ matrix.target }}

      - name: Create tar.gz
        run: tar -czvf tfreg_${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release tfreg

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: tfreg-${{ matrix.target }}
          path: tfreg_${{ matrix.target }}.tar.gz

  release:
    name: release
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: tmp

      - name: Prepare release directory
        run: mkdir bin && cp tmp/**/*.tar.gz bin && ls bin

      - name: Calculate SHA256SUMS
        run: pushd bin && sha256sum * > SHA256SUMS && popd

      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
